#! /usr/bin/env node
require('@babel/register');
const yargs = require('yargs');

const index = require('./index').default;

const argv = yargs
  .command('$0', 'Generate FFMETA file', b => b
    .option('chapters', { 
      alias: 'c', type: 'string',
      description: 'Path to a CSV file containing the chapter list. See README for more details.'
    })
    .option('title', { 
      alias: 't', type: 'string',
      description: 'The title to embed for the video.'
    })
    .option('author', { 
      alias: 'a', type: 'string',
      description: 'The author to embed for the video.'
    })
    .strict()
    .help()
  )
  .argv;

index(argv).catch(console.error);
